spring.application.name=SnipURL
spring.datasource.url=jdbc:postgresql://localhost:5432/snipurl
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.base-url=http://localhost:8080

# Welcome page configuration
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=          # ? Empty is correct for local
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# Cache TTL (1 hour in seconds)
app.cache.ttl=3600